--Artist Sequences
CREATE SEQUENCE Artist_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Fname_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Lname_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Artist_Fname_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Artist_Lname_Seq START WITH 100 INCREMENT BY 1 NOCACHE;

--Album sequences
CREATE SEQUENCE Album_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AlbumName_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AlbumType_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ReleaseDate_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Labels_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Genres_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Album_AlbumName_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Album_AlbumType_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Album_ReleaseDate_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Album_Labels_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Album_Genres_Seq START WITH 100 INCREMENT BY 1 NOCACHE;

--Song sequences
CREATE SEQUENCE Song_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SongName_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Song_SongName_Seq START WITH 100 INCREMENT BY 1 NOCACHE;

--Old table sequences
CREATE SEQUENCE Recording_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ArtistMakesRecording_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ArtistMakesAlbum_Seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ArtistMakesSong_Seq START WITH 100 INCREMENT BY 1 NOCACHE;